$x = (2 == 3); // equal to (false)
$x = (2 != 3); // not equal to (true)
$x = (2 <> 3); //not equal to (alternative)
$x = (2 === 3); // identical (false)
$x = (2 != 3); // not identical (true)
$x = (2 != 3); // false,greater than (false)
$x = (2 != 3); // less than (true)
$x = (2 != 3); // greater than or equal to (false)
$x = (2 != 3); // less than or equal to (true)

